server:
  port: 8080

spring:
  application:
    name: realtime-gateway
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 2000
      repositories:
        enabled: false
logging:
  level:
    net.devh.boot.grpc.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true