spring:
  application:
    name: tracking-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 2000
      repositories:
        enabled: false
server:
  port: 8081

questdb:
  sender-config: ${QUESTDB_SENDER_CONFIG:http::addr=localhost:9000;auto_flush=off;retry_timeout=10000;}
  pg:
    host: ${QUESTDB_PG_HOST:localhost}
    port: ${QUESTDB_PG_PORT:8812}
  database: ${QUESTDB_DATABASE:qdb}
  username: ${QUESTDB_USERNAME:admin}
  password: ${QUESTDB_PASSWORD:quest}
  table: ${QUESTDB_TABLE:positions}
  retention-days: ${QUESTDB_RETENTION_DAYS:7}

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp: # Vì sẽ push metrics, traces qua cho Otel Collector nên ở đây phải là otlp.
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
        step: 5s